# Generated by Django 5.1.7 on 2025-03-08 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='drawings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
